### ISSUE TITLE
Add Pull request templates

### ISSUE THREAD

**Issue by 2002Bishwajeet** [2002Bishwajeet/awesome-appwrite-snippets#10]
# Introduction

This repo is still quite new and needs some basic things to be set up properly.

This issue is all about adding Pull request templates. Your task is to add pull request templates. You can refer to this [PULL_REQUEST_TEMPLATE](https://github.com/appwrite/appwrite/blob/master/.github/PULL_REQUEST_TEMPLATE.md) from the official appwrite repo😄 . 

This [documentation from the Github](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) can also help you too.

## Task Summary

- [ ] Fork & clone this repository
- [ ] prepare pull request template in `.github/PULL_REQUEST_TEMPLATE.md`
- [ ] Push changes to master and test the pull request template on your fork
- [ ] Submit pull request

If you need any help, reach out to `#Maniac_Fighter#3747` on [Appwrite Discord server](https://discord.gg/GSeTUeA) or comment on this issue😉.

Are you ready to work on this issue? 🤔 Let me know, and I will assign it to you 😊

**Happy Contributing**✨

**Comment by Pranjalmishra30** [comment]
Hi I would like ti work on this issue.

**Comment by 2002Bishwajeet** [comment]
Sure @Pranjalmishra30 , go ahead😄 . All the best!! .
