### ISSUE TITLE
Add more client side SDKs

### ISSUE THREAD

**Issue by 2002Bishwajeet** [2002Bishwajeet/awesome-appwrite-snippets#11]
# Introduction
Awesome Appwrite Snippets is a collection of commonly used Appwrite APIs. It increases your speed of development by eliminating most of the boilerplate code associated with making using Appwrite in your Project.

Your task is to implement add snippets support for more client-side APIs.  You can look at the existing [snippets](https://github.com/2002Bishwajeet/awesome-appwrite-snippets/tree/master/snippets) in the coding language (for now _JS_ and _Dart_) you prefer to see how it works.

## Task Summary

- [ ] Fork & clone this repository
- [ ] create `feat-x-api-y-lang-snippet` branch where `x` is the REST-API you are implementing and `y` is the name of the language
- [ ] Write code in the folder `/snippets/client` where `client`  is the folder for which snippets you are adding (`web` for adding snippets for web platform). If the folder doesn't exist for the platform you are creating, create a new folder.
- [ ] Name should be in the form of `X.code-snippets` where `X` is the REST API (example: Account) in lowercase. Add the snippets. To add snippets refer to the [contributing.md](https://github.com/2002Bishwajeet/awesome-appwrite-snippets/blob/master/CONTRIBUTING.md#to-add-new-snippets) guide.
- [ ] Test your snippets locally. 
- [ ] (Optional) If everything works perfectly, it's time to update the readme section. Look at the [readme](https://github.com/2002Bishwajeet/awesome-appwrite-snippets/blob/master/README.md) to see the structure of how it's done. Applicable only for adding snippets for new APIs.
- [ ] Make a PR and just wait for the maintainer to review it😎.

If you need any help, reach out to `#Maniac_Fighter#3747` on [Appwrite Discord server](https://discord.gg/GSeTUeA) or comment on this issue😉.
Are you ready to work on this issue? 🤔 Let me know, and I will assign it to you 😊.  Since there are a lot of snippets to work on, this issue can be assigned to multiple people. You can add snippets in your favorite language🤯. When requesting to be assigned, please mention which language would you like to use.

## Assignees table
✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

|   REST APIs   | Flutter SDK | Web SDK | Apple SDK | Android SDK (Java) | Android SDK (Kotlin) |
| :-----------: | ----------- | ------- | --------- | ------------------ | -------------------- |
|    Client     | ✅          | ✅      |    ❌       |       ❌             |            ❌          |
|    Account    | ✅          | ✅      |    ❌       |      ❌              |           ❌           |
|   Database    | ✅          | ✅      |    ❌       |       ❌             |           ❌           |
|    Storage    | ✅          | ✅      |      ❌     |        ❌            |             ❌         |
|     Teams     | ✅          | ✅      |      ❌     |         ❌           |            ❌          |
|   Functions   |      ❌       |   ❌      |    ❌       |      ❌              |         ❌             |
| Localizations |     ❌        |   ❌      |     ❌      |         ❌           |       ❌               |
|    Avatars    |       ❌      |     ❌    |       ❌    |            ❌        |             ❌         |

**Happy Contributing** ✨

**Comment by RJ025** [comment]
hey @2002Bishwajeet  could you please assign this issue to me.

**Comment by 2002Bishwajeet** [comment]
Hey @RJ025 👋
What snippets you would like to work on??

**Comment by RJ025** [comment]
@2002Bishwajeet  functions one I would like to work on.

**Comment by 2002Bishwajeet** [comment]
Sure in which language?

**Comment by RJ025** [comment]
@2002Bishwajeet  file should be in JSON format.

**Comment by 2002Bishwajeet** [comment]
You can refer to the [contributing guide](https://github.com/2002Bishwajeet/awesome-appwrite-snippets/blob/master/CONTRIBUTING.md) and lemme know if anything's unclear

**Comment by RJ025** [comment]
hey @2002Bishwajeet  just made a PR please look into it

**Comment by 2002Bishwajeet** [comment]
Hey @RJ025 👋. Just checking out, are you still interested to work on this??

**Comment by RJ025** [comment]
@2002Bishwajeet  yes sorry for late submission I just created a PR for the issue please look into it

**Comment by 2002Bishwajeet** [comment]
Hey @GunjanGupta26 , go ahead. All the Best!! ✨
