### ISSUE TITLE
Add more Server side SDKs

### ISSUE THREAD

**Issue by 2002Bishwajeet** [2002Bishwajeet/awesome-appwrite-snippets#12]
# Introduction
Awesome Appwrite Snippets is a collection of commonly used Appwrite APIs. It increases your speed of development by eliminating most of the boilerplate code associated with making using Appwrite in your Project.

Your task is to implement add snippets support for more server-side APIs.  You can look at the existing [snippets](https://github.com/2002Bishwajeet/awesome-appwrite-snippets/tree/master/snippets) in the coding language (for now _JS_ and _Dart_) you prefer to see how it works.

## Task Summary

- [ ] Fork & clone this repository
- [ ] create `feat-x-api-y-lang-snippet` branch where `x` is the REST-API you are implementing and `y` is the name of the language
- [ ] Write code in the folder `/snippets/client` where `client`  is the folder for which snippets you are adding (`dart` for adding snippets for dart language). If the folder doesn't exist for the language you are creating, create a new folder.
- [ ] Name should be in the form of `X.code-snippets` where `X` is the REST API (example: Account) in lowercase. Add the snippets. To add snippets refer to the [contributing.md](https://github.com/2002Bishwajeet/awesome-appwrite-snippets/blob/master/CONTRIBUTING.md#to-add-new-snippets) guide.
- [ ] Test your snippets locally. 
- [ ] If everything works perfectly, it's time to update the readme section. Look at the [readme](https://github.com/2002Bishwajeet/awesome-appwrite-snippets/blob/master/README.md) to see the structure of how it's done. Applicable only for adding snippets for new APIs.
- [ ] Make a PR and just wait for the maintainer to review it😎.

If you need any help, reach out to `#Maniac_Fighter#3747` on [Appwrite Discord server](https://discord.gg/GSeTUeA) or comment on this issue😉.
Are you ready to work on this issue? 🤔 Let me know, and I will assign it to you 😊.  Since there are a lot of snippets to work on, this issue can be assigned to multiple people. You can add snippets in your favorite language🤯. When requesting to be assigned, please mention which language would you like to use.

## Assignees table
✅ = Done - This language has already been finished
⚒ = In progress - Someone is already working on this language
❌ = Unassigned yet - This language can be assigned to you

### Server Side

|   REST APIs   | Dart | Node.js | Swift | Deno | Python | Ruby | PHP | Kotlin |
| :-----------: | ---- | ------- | ----- | ---- | ------ | ---- | --- | ------ |
|    Client     | ✅   |   ❌       |  ❌          |   ❌        |    ❌         |   ❌        |  ❌        | ❌            |
|    Account    |  ❌     |     ❌     |  ❌          |   ❌        |    ❌         |  ❌         |   ❌       |  ❌           |
|   Database    |  ❌     |   ❌           |   ❌         |  ❌         |    ❌         |  ❌         | ❌         |  ❌           |
|    Storage    |   ❌    |    ❌          |   ❌         |  ❌         |    ❌         |   ❌        |  ❌        |   ❌          |
|     Teams     |   ❌    |     ❌         |   ❌         |   ❌        |    ❌         |  ❌         |  ❌        |    ❌         |
|   Functions   | ❌      |    ❌          |   ❌         |  ❌         |   ❌          |   ❌        | ❌         |   ❌          |
| Localizations | ❌      |    ❌          |   ❌         |  ❌         |     ❌        |  ❌         |   ❌       |     ❌        |
|    Avatars    |  ❌     |  ❌            |    ❌        |  ❌         |   ❌          |   ❌        |  ❌        |    ❌         |
|    Health     |  ❌     |  ❌            |     ❌       |  ❌         |    ❌         |  ❌         |  ❌        |    ❌         |
|     Users     |  ❌     |    ❌          |  ❌          |  ❌         |   ❌          |   ❌        |  ❌        |    ❌         |

**Happy Contributing** ✨

**Comment by Meldiron** [comment]
@2002Bishwajeet Hey there 👋 I would love to work on PHP snippets 😇

**Comment by 2002Bishwajeet** [comment]
Hey @Meldiron 👋, Assigned to you. All the best😄

**Comment by Rajat379** [comment]
Hey @2002Bishwajeet, wouldn't the dart snippets be similar (or same) compared to the ones in flutter?

**Comment by 2002Bishwajeet** [comment]
> Hey @2002Bishwajeet, wouldn't the dart snippets be similar (or same) compared to the ones in flutter?

I agree that some APIs are common with the Flutter Client SDK and Dart Server SDK but there are many more services and APIs are present which isn't present inside the Client SDK so its best to have a separate category for it

**Comment by Rajat379** [comment]
Okay so should I firstly make a single PR covering all the cases of Dart Server ones which are overlapping?

**Comment by 2002Bishwajeet** [comment]
> Okay so should I firstly make a single PR covering all the cases of Dart Server ones which are overlapping?

Yep, you should follow the similar standard. However, I would recommend you make snippets for a single service in a PR. Lemme know which one you wanna work on and I will assign it to you🙂

**Comment by Rajat379** [comment]
Sure I have a raised a PR covering the account API snippet in Dart.

**Comment by adityaoberai** [comment]
Happy to help out with Kotlin serverside API snippets :)

**Comment by pranavajith** [comment]
Hey @2002Bishwajeet 
I'd like to take upon this issue.

**Comment by 2002Bishwajeet** [comment]
Hey @pranavajith, assigned to you. Lemme know on which language you wanna work on?

**Comment by pranavajith** [comment]
@2002Bishwajeet 
Python or node... depending on which is more applicable.

**Comment by pranavajith** [comment]
I'm down to learning new languages as well... Would really like to use this opportunity to level up and gain a new skill.

**Comment by 2002Bishwajeet** [comment]
How about you work on making snippets for Client and Account for now in Python? If everything looks good you can work on more snippets as well once you make the PR😉

**Comment by pranavajith** [comment]
Sure.. seems great. So I'll unassign myself from the server side issue and you could assign me to the client side?

**Comment by 2002Bishwajeet** [comment]
I meant working on the client and account snippets of the server SDKs only.

**Comment by pranavajith** [comment]
Sounds great.. is it cool if I reach out to you on discord, in case of any doubts? Might be easier to communicate there.

**Comment by 2002Bishwajeet** [comment]
yea sure

**Comment by pranavajith** [comment]
<img width="576" alt="Screenshot 2022-12-05 at 8 31 40 PM" src="https://user-images.githubusercontent.com/96235918/205669553-53b48a2b-251e-4402-b0de-49df2eeae089.png">


Is this fine, @2002Bishwajeet ? Any editing necessary for server side client snippets?

**Comment by 2002Bishwajeet** [comment]
Looks fine

**Comment by 2002Bishwajeet** [comment]
Hey @pranavajith, lemme know if you are still working on this issue?
