### ISSUE TITLE
Add GitHub issue forms

### ISSUE THREAD

**Issue by 2002Bishwajeet** [2002Bishwajeet/awesome-appwrite-snippets#9]
# Introduction

GitHub has rolled out a [public beta for their issue forms](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) feature last year. This would allow you to create interactive issue templates and validate them ✨.

Awesome Appwrite Snippets currently does not have any issue template format Your task is to create GitHub issue forms for this repository. Please use [Appwrite's issue templates](https://github.com/appwrite/appwrite/tree/master/.github/ISSUE_TEMPLATE) as a reference for this PR.

### Tasks summary:

- [ ]  Fork & clone this repository
- [ ] Prepare bug report issue form in `.github/ISSUE_TEMPLATE/snippet_bug.yaml`
- [ ] Prepare documentation issue form in `.github/ISSUE_TEMPLATE/documentation.yaml`
- [ ] Prepare feature request issue form in `.github/ISSUE_TEMPLATE/feature.yaml`
- [ ] Push changes to master and test issue forms on your fork
- [ ] Submit pull request

If you need any help, reach out to `#Maniac_Fighter#3747` on [Appwrite Discord server](https://discord.gg/GSeTUeA) or comment on this issue😉.

Are you ready to work on this issue? 🤔 Let me know, and I will assign it to you 😊

**Happy Contributing**✨

**Comment by Nikhil-1503** [comment]
Hey, I would like to work on this.

**Comment by 2002Bishwajeet** [comment]
Hey @Nikhil-1503, assigned to you. All the best😉
